# Generated by Django 5.0.6 on 2024-05-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('universidad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('ciclo', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('usuario.usuario',),
        ),
    ]
