# Generated by Django 5.0.6 on 2024-05-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='estudiante.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='profesor.profesor')),
            ],
            options={
                'unique_together': {('estudiante', 'profesor')},
            },
        ),
    ]
